CREATE DATABASE BDTRES

USE BDTRES

-- LAS DOS LINEAS ANTERIORES SON PARA CONFIGURAR ADECUADAMENTE LA BASE DE DATOS Y LAS SENTENCCIAS SE PUEDAN EJECUTAR
SELECT * FROM

INSERT DEMO11 VALUES (33,'12345689456','2007-12-20')

GO
------------EJEMPLO------------
CREATE TABLE DEMO12(
CODIGO INT IDENTITY(20,1),
DATO1 VARCHAR (30),
DATO2 VARCHAR (30),
DATO3 NVARCHAR(30))

GO
INSERT DEMO12 VALUES ('LEONARDO','DANIEL','PATRICIO')
GO
SELECT*FROM DEMO12
-------------- OTRO EJEMPLO--------

CREATE TYPE DBO.APELLIDO FROM VARCHAR(30) NULL		-- estamos creando un tipo de dato: apellido...
GO
CREATE TABLE DEMO13(
CODIGO INT IDENTITY(100,3),
NOMBRES VARCHAR(40),
AP_PATERNO APELLIDO,
AP_MATERNO APELLIDO)

GO
INSERT DEMO13 VALUES ('DANIEL','RAMOS','CASTAÑEDA')
GO
SELECT *FROM DEMO13
GO
EXEC SP_HELP DEMO13
GO
SELECT*FROM SYS.TABLES  --MUESTRA LAS TABLAS EXISTENTES
GO
DROP TYPE DBO.APELLIDO  --PARA BORRAR UN TIPO DE DATO --> APELLIDO
--Pero tipo de dato apellido no puede borrarse porque esta en uso.
-----------------ejemplo3---------
GO
CREATE TABLE AGENDA1(
CODIGO INT IDENTITY(100,3), --FIJO -- ESTOS NUMEROS (100,3) me dice que mi codigo identificador comenzará en 100 y crecera de 3 en 3.
NOMBRE VARCHAR (100),  -- VARIA
NACIMIENTO DATETIME, -- FIJO
SEXO CHAR(1) NOT NULL,   --FIJO
DIRECCION VARCHAR(200), -- VARIA
DISTRITO VARCHAR(30)) NOT NULL -- VARIA
GO
INSERT AGENDA1 VALUES('NATY','1989-05-22','F','XXX','VES')
INSERT AGENDA1 VALUES('ELI','1986-02-22','F','SSSS','SJL')
INSERT AGENDA1 VALUES('ANGIE','1972-08-17','F','NNNN','SJL')
INSERT AGENDA1 (NOMBRE,SEXO) VALUES ('DANIEL','G')
INSERT AGENDA1 VALUES(NULL,NULL,NULL,NULL,NULL)
GO
SELECT * FROM AGENDA1

CREATE TABLE AGENDA2(
CODIGO INT IDENTITY(100,3), --FIJO -- ESTOS NUMEROS (100,3) me dice que mi codigo identificador comenzará en 100 y crecera de 3 en 3.
NOMBRE VARCHAR (100) NOT NULL,  -- VARIA
NACIMIENTO DATETIME, -- FIJO
SEXO CHAR(1) NOT NULL,   --FIJO
DIRECCION VARCHAR(200), -- VARIA
DISTRITO VARCHAR(30))


--AGREGANDO CAMPOS A LA AGENDA 2 QUE ES UNA TABLA)

ALTER TABLE AGENDA2 ADD FONO VARCHAR (30) -- ESTAMOS AGREGANDO EL CAMPO O COLUMNA FONO

ALTER TABLE AGENDA2 ADD EMAIL VARCHAR (120) -- ESTAMOS AGREGANDO EL CAMPO O COLUMNA EMAIL


INSERT AGENDA2 VALUES('NATY','1989-05-22','F','XXX','VES')
INSERT AGENDA2 VALUES('ELI','1986-02-22','F','SSSS','SJL')
INSERT AGENDA2 VALUES('ANGIE','1972-08-17','F','NNNN','SJL')
INSERT AGENDA2 (NOMBRE,SEXO) VALUES ('DANIEL','G')
INSERT AGENDA2 VALUES(NULL,NULL,NULL,NULL,NULL)
SELECT * FROM AGENDA2

ALTER TABLE AGENDA2 DROP COLUMN SEXO

INSERT AGENDA2 (NOMBRE,FONO) VALUES ('CAREVERGA','1236523')

SELECT * FROM AGENDA2

SELECT @@IDENTITY  -- ES UNA VARIABLE DEL SISTEMA...ESTA VARIABLE ALMACENA EL ULTIMO VALOR IDENTITY GENERADO.

SELECT NEWID() -- DEVUELVE UN VALOR DE 16 BYTE EN FORMATO HEXADECIMAL


create table transaccion(
nrotran INT IDENTITY (2,3),
CODTRAN UNIQUEIDENTIFIER DEFAULT NEWID (),
DATO VARCHAR (30),
FECHA DATETIME DEFAULT GETDATE())
GO
INSERT TRANSACCION(DATO)VALUES('LECHE')
INSERT TRANSACCION(DATO)VALUES('MANTEQUILLA')
GO
SELECT *FROM TRANSACCION
GO
CREATE TABLE DEMO14(
CODIGO INT IDENTITY(1,1),
DATO1  VARCHAR(30) DEFAULT 'XXX',
DATO2 VARCHAR (30),
FECHA DATETIME DEFAULT GETDATE ())
GO
INSERT DEMO14 VALUES ('HOLA','HELLO','1994-05-14')
INSERT DEMO14(DATO2) VALUES ('CARAMBA')
GO
SELECT*FROM DEMO14

-----------USO DEL CHECK------------
CREATE TABLE AGENDA3(
CODIGO INT IDENTITY(100,3), --FIJO -- ESTOS NUMEROS (100,3) me dice que mi codigo identificador comenzará en 100 y crecera de 3 en 3.
NOMBRE VARCHAR (100) NOT NULL,  -- VARIA
NACIMIENTO DATETIME, -- FIJO
SEXO CHAR(1) CHECK (SEXO IN ('M','F')))  --FIJO

GO

INSERT AGENDA3 VALUES ('DANIEL','1972-1-18','m') --PUEDE SER MAYUSCULA O MINUSCULA

go
select * from AGENDA3

GO
USE master
GO
CREATE DATABASE PRUEBA

CREATE TABLE DEMO15(
CODALUMNO INT IDENTITY (200,53),
NOMALUMNO VARCHAR(50) NOT NULL,
NOTA1 INT CHECK (NOTA1>=0 AND NOTA1<=20))

GO
INSERT DEMO15 VALUES ('MARICONCITO',13)
INSERT DEMO15 VALUES ('CABRITO',20)
INSERT DEMO15 VALUES ('ROSQUITA',16)
INSERT DEMO15 VALUES ('GAYCITO',08)
INSERT DEMO15 VALUES ('ANGELITO',23)
SELECT * FROM DEMO15
--- Borrar una tabla-----
DROP TABLE DEMO15 -- HEMOS BORRADO LA TABLA DEMO15


CREATE TABLE ALUMNO(
CODALU INT IDENTITY (1,1) PRIMARY KEY,
NOMALU VARCHAR(80) NOT NULL,
DNI VARCHAR (8) UNIQUE,
SEXO CHAR (1) CHECK (SEXO IN ('M','F')))

GO
INSERT ALUMNO VALUES ('KOKO GILES','45852461','M')
GO
SELECT * FROM ALUMNO

CREATE TABLE ALUMNO2(
CODALU INT PRIMARY KEY,
NOMALU VARCHAR(80) NOT NULL,
DNI VARCHAR (8) UNIQUE,
SEXO CHAR (1) CHECK (SEXO IN ('M','F')))

GO
INSERT ALUMNO2 VALUES (7,'KOKO GILES','45852452','M')

GO
SELECT * FROM ALUMNO2