SELECT @@SERVERNAME   -- NOMBRE DEL SERVIDOR
GO
SELECT HOST_NAME()  -- NOMBRE DEL PC CLIENTE
GO
SELECT SUSER_SNAME()  -- NOMBRE DEL USUARIO
GO
SELECT GETDATE()    -- FECHA Y HORA DEL SERVIDOR
GO
EXEC SP_HELPDB  -- MUESTRA LAS BD EXISTENTES

SELECT * FROM SYS.DATABASES
GO
EXEC SP_HELPDB MODEL

SELECT DB_NAME()
GO
---- CREANDO UNA BASE DE DATOS
CREATE DATABASE EJEMPLO11
GO
SELECT * FROM SYS.DATABASES
GO
exec SP_HELPDB EJEMPLO11
--- CREANDO LA BD 
CREATE DATABASE EJEMPLO12
ON (   -- ARCHIVO DE DATOS
NAME='EJEMPLO12_DATA',    -- NOMBRE INTERNO
FILENAME='E:\CLASESQL\EJEMPLO12.mdf', --FISICO
SIZE=5,    -- TAMAÑO INICIAL
MAXSIZE=10,   -- TAMAÑO MAXIMO
FILEGROWTH=2 )  --CRECIMIENTO DEL ARCHIVO
LOG ON (   -- ARCHIVO DE TRANSACCIONES
NAME='EJEMPLO12_LOG',
FILENAME='E:\CLASESQL\EJEMPLO12.LDF',
SIZE=1,
MAXSIZE=3,
FILEGROWTH=1 )

