SELECT HOST_NAME()
GO
SELECT SUSER_NAME() --NOMBRE DEL USUARIO
GO
SELECT GETDATE() --FECHA Y HORA DEL SERVIDOR
GO
EXEC SP_HELPDB -- MUESTRA LAS BASES DE DATOS EXISTENTES

SELECT*FROM SYS.DATABASES 
GO

SP_HELPDB Banco -- NOS MUESTRA INFORMACIÓN SOBRE UNA BASE DE DATOS EN ESPECIAL

SELECT DB_NAME()
GO
--- CREANDO UNA BASE DE DATOS

CREATE DATABASE EJEMPLO11
GO
EXEC SP_HELPDB EJEMPLO11


--- CREANDO UNA BASE DE DATOS (BD) 

CREATE DATABASE EJEMPLO12
ON(												--ARCHIVO DE DATOS
NAME='EJEMPLO12_DATA',								--NOMBRE INTERNO
FILENAME='E:\CLASESQL\EJEMPLO12.mdf',				--FISICO
SIZE=5,												--TAMAÑO INICIAL
MAXSIZE=10,											--TAMAÑO MAXIMO
FILEGROWTH=2)										--CRECIEMIENTO DEL ARCHIVO

LOG ON (											--ARCHIVO DE TRANSACCIONES
NAME='EJEMPLO12_LOG', 
FILENAME='E:\CLASESQL\EJEMPLO12.LDF',
SIZE=1,
MAXSIZE=3,
FILEGROWTH=1)